package ExceptionHandling;

public class Throw_ExceptionExample {
    public  void sample(){
        System.out.println("inside sample methode before throwing exception");
    }
    public static void main(String[] args) {

    }
}
